{{- if .Values.allow_from_gateway.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-istio-ingressgateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway
  action: ALLOW
  rules:
    - to:
        - operation:
            paths: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-gateway-sa
  namespace: {{ .Release.Namespace }}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/{{ .Values.allow_from_gateway.istio_system_namespace }}/sa/{{ .Values.allow_from_gateway.istio_gateway_service_account }}"]
{{- end }}